name: Scrap Ten Jokes everyday
# run scrap.js to add new jokes everyday to the database
on:
  schedule:
    - cron : "10 05 * * *"
    # run at 510 AM UTC Everyday
  workflow_dispatch:
jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Setup node modules
        env:
          API_NINJAS_API_KEY : ${{ secrets.API_NINJAS_API_KEY }}
        
        run: |
          npm install
          node scrap.js 10
          node scrap.js facts 10
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily Scrap
